#!/usr/bin/env python


"""
Two ways to put in bin

- copy this file into bin and change libdir below
OR
- Use a symlink
  ln -s /this/file/path /bin/path/dotmagic

"""

import os, sys

libdir = "/Users/minghan/Documents/hanworks/" # base dir

if libdir not in sys.path:
    sys.path.insert(0, libdir)

#import dotmagic.dispatch
import dispatch

dispatch.run()


